DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT (id bigint generated BY DEFAULT AS IDENTITY default on null, item_date DATE,  item VARCHAR(255),
income INTEGER NOT NULL,expense INTEGER NOT NULL,  note VARCHAR(255),PRIMARY KEY (id));

INSERT INTO ACCOUNT(item_date, item, income, expense, note)
VALUES('2022-02-02','T-Shirts',1000,1000,'Uniqlo T-Shirt'),
('2022-02-03','iPhone',2000,2000,'iPhone 13 Pro'),
('2022-02-04','Green Curry',3000,3000,'Thai Cuisine');
